### ISSUE TITLE
Convert notebooks to myst markdown

### ISSUE THREAD

**Issue by amcdawes** [amcdawes/qutip-book#5]
per email from @nathanshammah 
Pros: nice for pull request review
Cons: adds a little step if folks are not acquainted with them (having the jupytext extension in jupyter notebook makes them render).

(myst is used for Unitary Fund documentation)

**Comment by hodgestar** [comment]
A quick link to the Jupyter Book docs on using MyST with Jupyter Book -- https://jupyterbook.org/file-types/myst-notebooks.html

**Comment by amcdawes** [comment]
Thanks, I have the notebooks ported over to myst as of the last commit

Best,
Andy

**Comment by amcdawes** [comment]
This should be done as of bc8efe5898123eff4f4e8daa17d0b55c56d7f4dd
